# Generated by Django 3.2.4 on 2021-07-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='banner',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
