# Generated by Django 3.2.4 on 2021-07-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210728_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='banner',
            new_name='image',
        ),
    ]
