# Generated by Django 3.2.4 on 2021-08-10 16:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Pending', 'Pending'), ('Order Received', 'Order Received'), ('Preparing', 'Preparing'), ('Onshiping', 'Onshiping'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=255, null=True),
        ),
    ]
