# Generated by Django 3.2.4 on 2021-08-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
